# Catégories
categorie:
    resource: "@ZertzSortBundle/Controller/CategoryController.php"
    prefix: /{_locale}/trouver
    defaults: { _locale: fr }
    type: annotation
    requirements:
        _locale: fr|en