services:
    zertz.sort_listener:
        class: Zertz\SortBundle\EventListener\SortListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
